# Generated by Django 2.2.12 on 2020-08-19 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0003_add_posts'),
        ('photos', '0001_add_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_important', models.BooleanField(default=False, verbose_name='Post is important')),
                ('is_reacted', models.BooleanField(default=False, verbose_name='Somebody has already reacted on the post')),
                ('note', models.TextField(blank=True, max_length=255, verbose_name='Additional notes')),
                ('move', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='moves.MoveLog', verbose_name='MoveLog')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
