# Generated by Django 2.2.12 on 2020-08-19 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_add_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='photos.Photo', verbose_name='Photo'),
        ),
    ]
