# Generated by Django 2.2.12 on 2020-05-24 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_add_companies_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_cameras', related_query_name='from_camera', to='companies.Room', verbose_name='Камера на выходе в помещение')),
                ('to_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_cameras', related_query_name='to_camera', to='companies.Room', verbose_name='Камера на входе в помещение')),
            ],
            options={
                'verbose_name': 'Камера',
                'verbose_name_plural': 'Камеры',
            },
        ),
        migrations.CreateModel(
            name='MoveLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', related_query_name='log', to='moves.Camera', verbose_name='Запись о том, что человек прошел через камеру')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', related_query_name='log', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
