# Generated by Django 2.2.12 on 2020-08-19 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0002_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movelog',
            options={'ordering': ['-date'], 'verbose_name': 'MoveLog', 'verbose_name_plural': 'MoveLog'},
        ),
        migrations.AlterField(
            model_name='movelog',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', related_query_name='log', to='moves.Camera', verbose_name='Camera'),
        ),
        migrations.AlterField(
            model_name='movelog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='movelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', related_query_name='log', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
