"""
Django settings for facein_api project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
from settings.api_doc import *
from settings.databases import *
from settings.django import *
from settings.localization import *
from settings.rest import *
from settings.redis import *
from settings.static import *
