# Generated by Django 2.2.12 on 2020-05-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_custom_user_model'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('is_blacklisted', False), ('is_superuser', False), _negated=True), name='superusers_are_not_blocked'),
        ),
    ]
