# Generated by Django 2.2.12 on 2020-05-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_add_custom_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as admin of the customer company. ', verbose_name='admin status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_blacklisted',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. ', verbose_name='black list status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_security',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as security guard of the customer company. ', verbose_name='security status'),
        ),
    ]
