# Generated by Django 2.2.12 on 2020-05-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_user_model_update'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='superusers_are_not_blocked',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('is_blacklisted', True), ('is_superuser', True), _negated=True), name='superusers_are_not_blocked'),
        ),
    ]
