# Generated by Django 2.2.12 on 2020-05-19 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='FaceIn', max_length=255, verbose_name='Компания')),
                ('is_active', models.BooleanField(default=True, help_text='Компания пользуется услугами в данный момент', verbose_name='Активная')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Помещение')),
                ('info', models.TextField(blank=True, max_length=1023, verbose_name='Описание комнаты')),
                ('is_whitelisted', models.BooleanField(default=False, help_text='В помещение может попасть определенный круг людей (иначе все, кроме черного списка)', verbose_name='Помещение с белым списком')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', related_query_name='room', to='companies.Company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BlackWhiteList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_blacklisted', models.BooleanField(default=False, verbose_name='В черном списке')),
                ('is_whitelisted', models.BooleanField(default=False, verbose_name='В белом списке')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lists', related_query_name='user_list', to='companies.Room', verbose_name='Помещение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', related_query_name='room', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Черный и Белый Списки Помещения',
                'verbose_name_plural': 'Черный и Белый Списки Помещений',
                'unique_together': {('room', 'user')},
            },
        ),
    ]
