# Generated by Django 2.2.12 on 2020-05-24 16:34

from django.db import migrations


def create_main_company(apps, schema_editor):
    """
    Automatically create company FaceIn.
    """
    Company = apps.get_model('companies', 'Company')
    Company.objects.create(
        name='FaceIn',
        is_active=True
    )


def remove_main_company(apps, schema_editor):
    Company = apps.get_model('companies', 'Company')
    Company.objects.filter(name='FaceIn').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_add_companies_rooms'),
    ]

    operations = [
        migrations.RunPython(create_main_company, remove_main_company)
    ]
